<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

# Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

### Task2
- Raise 2 to the power 10

In [ ]:
print("the value of 2**10 is : ", end=" ")
print(pow(2, 10))


the value of 2**10 is :  1024


### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [ ]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]
print("the original list : " + str(list1))
res =[list1[i]  for i in range(len(list1)) if i % 2!=0]
print("the alternate element  list is : " + str(res))

the original list : ['India', 'Japan', 'Singapore', 'China', 'Australia', 'Africa', 'Dubai', 'France', 'Italy', 'Germany']
the alternate element  list is : ['Japan', 'China', 'Africa', 'France', 'Germany']


 DESCRIPTION:-Shorthand to the naive method, list comprehension provides a faster way to perform this particular task. In this method, all the indices which are not multiple of 2, hence odd are inserted in the new list
 

In [6]:
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]


index_list = [1, 4, 5, 8] 

  
# printing original lists 

print ("Original list : " + str(list1)) 

print ("Original index list : " + str(index_list)) 

  
# using list comprehension to  
# elements from list  

res_list = [list1[i] for i in index_list] 

      
# printing result 

print ("Resultant list : " + str(res_list))


Original list : ['India', 'Japan', 'Singapore', 'China', 'Australia', 'Africa', 'Dubai', 'France', 'Italy', 'Germany']
Original index list : [1, 4, 5, 8]
Resultant list : ['Japan', 'Australia', 'Africa', 'Italy']


DESCRIPTION:-list comprehension 
This task is easy to perform with a loop, and hence shorthand for it is the first method to start with this task. Iterating over the index list to get the corresponding elements from list into new list is brute method to perform this task.

### Task4

- From the given list, extract the "Hex" and print it

In [7]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ] #GIVEN LIST2
a= (list2[2][2][2]) #access list of list
b=a[0]           
print('"',b,'"' [0]) #print HEX in between "" 


" Hex "


DESCRIPTION:-thire is given list list1 and then we acess the list of list of list  contain by "a" then acess element name contain by "b" then print Hex  in between " "

### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [8]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]}
a= dict1["Tevatron"][3]["Projects"][1]
print('"',a,'"')

" TOPD "


DESCRIPTION:-Thire is given dictionary name is dict1 and then in next step we acess the TOPD  then print  TOPD in between " " 

### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [13]:



n=int(input())
if n<=167:
    print("Short")
elif(n<=168 and n>=182):
    print("Average")
else
     (n<=182):
     print("Tall")
 
    

SyntaxError: invalid syntax (1423429773.py, line 6)

DESCRIPTION:-with the help of input() function then we take the input and apply the contitions and provide limites  then acording to user input then provide output hight is short ,long, average

### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [ ]:

a="banana"
print(a.upper())



BANANA


DESCRIPTION:- thire is a is contain the the element banana and then with the help of upper() then we print the banana in capital letter

### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [ ]:
import random
a=(random.randrange(100,200))
print(a)


161


DESCRIPTION:-random.random range is print the any  value  randomly in between 100 to 200 

### Task9

Print all even integers from the array created in Task8

In [ ]:
import numpy as np
x = np.arange(100,202,2)
print(x)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]


DESCRIPTION:-with the help of this np.arrange(100,202,2) thire range is print all even integers from the array  between 100 to 202  but thire becouse of 2 print only 100 to 200   

### Task10

Print all 100 values from Standard Normal Distribution

In [ ]:
import numpy as np
r=np.random.normal(size=100)
print(r)

[-1.67774917  0.78695658 -1.4422983  -1.66199747 -1.10395296  0.17056898
  2.0583152  -0.17417637 -0.70262899  0.85074297 -0.38037147 -1.12210779
 -0.08610631  0.57632202  0.34593143  2.35936505 -0.15818205 -1.19361955
  0.20586249  0.56007203  0.95260824 -0.01205917  0.57196951 -0.21410429
 -0.37447799 -0.82272526  0.72016809 -2.70551611 -0.24410175  2.11280242
  1.99829437  0.16145277  0.62574168 -1.44383662  0.9922016   0.81967042
  0.07002482  0.76859512 -0.74410322 -1.22963653  2.41148754  0.3137655
  0.58645387 -0.62994682  0.55034096  1.88638884  0.40574187 -0.86069565
 -0.47590035  0.50283922 -0.34118117 -0.60552609 -0.54564831 -0.78685565
 -2.15450824  1.01697759 -1.68963684 -0.24519979  0.50808612 -0.78950482
 -0.93949324  0.03995721 -0.16379534  0.38416669  0.56080884  0.90451578
  0.33008517  1.38478146 -0.7257176   0.79896346  1.62731587 -0.48428566
 -0.74447633  0.29076424 -1.58137308  1.52564381  0.21079288  0.86189584
  0.5428264   0.09471559  0.93711303  1.36487151 -0.

DESCRIPTION:-thire  r is cantain np.random.normal(size=100)  thire is standard normal distribution size=100 is define then print r 

### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [ ]:
import numpy as np
rand_array=np.random.randint(0,7,4)
print(rand_array)


[3 2 0 0]


DESCRIPTION:-randint() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high) and random is provide and any randomly numbers whose dimension attribute is equal to 4

### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [ ]:
import numpy as np
array=np.arange(10,22,2)
print(array)

[10 12 14 16 18 20]


DESCRIPTION:-np.arange() thire np  is numpy and arange(10,22,2) is arange the numpy array of 100 values which is evenly space between 10 to 20 

### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [ ]:

import numpy as np
array=np.ones((5,5))
print(array)
print(" print last 3 rows")
print (array[2:5])

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 print last 3 rows
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


DESCRIPTION:-ones() becouse of this thire is print 5*5 numpy array is cantaine values then print the array after print last 3 rows which is 3 to 5 then in the next step we will print the array rows 2 to 5 

### Task14

Using the array created above in Task13, Print the first 2 columns

In [ ]:

import numpy as np
array=np.ones((5,5))
print(array)
print(" print first 2 columns")
array1=array[:,[0,1]]
print (array1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 print first 2 columns
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


DESCRIPTION:- one()  pint matrix 5*5which is cantain 1 after then thire is print first 2nd columns

### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [ ]:
import random as ran
r=[ran.random()for i in range(1,25)]
print(sum(r))
print(min(r))
print(max(r))


12.31931035580251
0.04580672770902994
0.9269477678771173


DESCRIPTION :- thire is firstly cantaine the random array in the given range then print the sum of all elements and print the elements with max value and min values

### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

In [ ]:
import pandas as pd

dict1= {"D1":[0,1,2], 
        "D2":[3,4,5]}
dict2={"D3":[10,11,12],
       "D4":[13,14,15]}
dfl=pd.DataFrame(dict1,index=["R0","R1","R2"])
dfr=pd.DataFrame(dict2,index=["R0","R1","R3"])


dfl.join(dfr,how="outer") 




            

D1   D2    D3    D4
R0  0.0  3.0  10.0  13.0
R1  1.0  4.0  11.0  14.0
R2  2.0  5.0   NaN   NaN
R3  NaN  NaN  12.0  15.0

DESCRIPTION:-thire is create the  dictanary by name dict1 and dict2 which is cantaine the row values and coloum also and print 

### Task17
Read car_sales.csv

In [ ]:
import pandas as pd
dt = pd.read_csv("car_sales (1).csv")
type(dt)

pandas.core.frame.DataFrame

DESCRIPTION :-pd.read_csv("car_sales (1).csv") read the  all over the date of file which is written in  between" "  then print the file type also

### Task18
Sort data frame in ascending order of the Price column

In [ ]:
import pandas as pd
dt = pd.read_csv("car_sales (1).csv")
type(dt)

dt.sort_values(by=["Price"],inplace=True)
print(dt)




    Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
30          31           Ford   Festiva    Small        6.9    7.4        7.9   
43          44        Hyundai     Excel    Small        6.8    8.0        9.2   
52          53          Mazda       323    Small        7.4    8.3        9.1   
38          39            Geo     Metro    Small        6.7    8.4       10.0   
79          80         Subaru     Justy    Small        7.3    8.4        9.5   
..         ...            ...       ...      ...        ...    ...        ...   
3            4           Audi       100  Midsize       30.8   37.7       44.6   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   

    MPG.city  MPG.highway  

DESCRIPTION :- thire is firstly read the file  car_sales (1).csv then print the file data after then short the only price coloumn in ascending order

### Task19
Print number of unique car manufacturers in the data

In [ ]:
import pandas as pd
dt = pd.read_csv("car_sales (1).csv")
type(dt)
print(dt["Manufacturer"].nunique())

32


DESCRIPTION :-read the file with the help of file name then  print unique car manufacturing  in car data 

### Task20
Print the maximum Wheelbase from the data

In [14]:
import pandas as pd
Wheelbase=[102,115,102,106,109,105,111,116,108,114,111,101,103,101,108,110,111,116,96,113,104,110,98,97,104,112,105,97,98,113,90,98,100,101,103,119,106,114,93,97,
            100,103,107,94,98,94,104,113,103,106,109,117,97,98,103,110,96,105,110,95,113,98,107,96,103,112,104,103,105,110,111,97,99,101,101,108,111,99,102,90,97,102,93,94,99,103,113,93,115,103,97,104,105
]
print(max(Wheelbase))




119


DESCRIPTION:- thire is firstly write the Wheelbase index values then print the max wheelbase

### Task21
Print the car Model which has maximum Wheelbase

In [66]:

import pandas as pd

dt = pd.read_csv("car_sales (1).csv")
type(dt)

print(dt)
print(max(Wheelbase))

    Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0            1        Acura  Integra    Small       12.9   15.9       18.8   
1            2        Acura   Legend  Midsize       29.2   33.9       38.7   
2            3         Audi       90  Compact       25.9   29.1       32.3   
3            4         Audi      100  Midsize       30.8   37.7       44.6   
4            5          BMW     535i  Midsize       23.7   30.0       36.2   
..         ...          ...      ...      ...        ...    ...        ...   
88          89   Volkswagen  Eurovan      Van       16.6   19.7       22.7   
89          90   Volkswagen   Passat  Compact       17.6   20.0       22.4   
90          91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7   
91          92        Volvo      240  Compact       21.8   22.7       23.5   
92          93        Volvo      850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers L

### Task22

Print the Details of car with maximum passenger capacity